//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.18 at 10:17:16 AM SAST 
//


package za.co.sizwe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.sizwe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Joe_QNAME = new QName("", "Sizwe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.sizwe
     * 
     */
    public ObjectFactory() {
    }

    public za.co.sizwe.StudentMarks createStudentMarks() {
        za.co.sizwe.StudentMarks studentMark = new za.co.sizwe.StudentMarks();
        return studentMark;
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link main.java.co.za.sizwe.StudentMarks }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "joe")
    public JAXBElement<za.co.sizwe.StudentMarks> createJoe(za.co.sizwe.StudentMarks value) {
        return new JAXBElement<>(_Joe_QNAME, za.co.sizwe.StudentMarks.class, null, value);
    }

}
